spring:
  datasource:
    username: springstudent
    password: springstudent
    url: jdbc:mysql://localhost:3306/spring
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        show_sql: true
        
server:
  port: 9092